Add rmv
aeon9300/To-Do-List pull request #4
Opened 2022-01-27 07:50 UTC by aeon9300

Add and remove feature in to-do-list

2022-01-27 09:16 UTC, dasileker requested changes
### **Hi  @aeon9300,** 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-27 09:16 UTC, dasileker commented on src/components/TaskListItem.js
> +        btnIsCompleted.parentNode.nextSibling.nextSibling.style.textDecoration = '';
- [ ] still, the task renders false if the check-box is clicked, it doesn't return true

![Capture d’écran 2022-01-27 101146](https://user-images.githubusercontent.com/61562626/151327998-f64e8169-e77d-4906-8567-95d0052bd26f.png)

2022-01-27 09:16 UTC, dasileker commented on src/components/TaskListItem.js
> +      // to the end of existing text in contentEditable HTML5 elements.
- [ ] Also I can't edit the task, it returns to the initial after refreshing.

2022-01-28 16:17 UTC, brytebee requested changes
Hi, @aeon9300 👋, 

Great work on making the changes 👏 👏 
You've done well implementing some of the requested changes requested by the previous review, but there are still some which aren't addressed yet.


# Suggested changes
_Check the comments under the review._

![](https://media.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-01-28 16:17 UTC, brytebee commented on README.md
> +![screenshot](#)
- [ ] **Optional:** Please attach a screenshot for a visual of your project.

2022-01-28 16:17 UTC, brytebee commented on src/components/TaskListItem.js
> +        btnIsCompleted.checked = true;
- [ ] **Required** The value of `isCompleted`  still doesn't change to true when clicked, please revisit your approach from when the item object(description, completed, index) is created to the point where you try to make the change between states.

![state false is unchanged](https://user-images.githubusercontent.com/27709832/151581971-846f1593-21af-4637-84f1-3f51434af965.gif)

2022-01-28 16:17 UTC, brytebee commented on src/components/CreateNewTaskItem.js
> +  form.innerHTML = `<input type="text" name="newTask" placeholder="Add new task ..." required/>
- [ ] **Optional:** Consider clearing the input field every time an item is added to the list, this would be better for UX.

2022-01-29 17:03 UTC, ShoiraTa approved these changes
### **STATUS: APPROVED  ✔️** 
------
Hi @aeon9300 ,  

Your project is complete! .. it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

<img src="https://www.serialminds.com/wp-content/uploads/2015/11/loser.gif" width="400" height="250" />

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-02 07:24 UTC, merged